/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ServerProject;

import ServerProject.ServerHandler;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author eh5i0
 */
public class ServerManu extends javax.swing.JFrame {

    /**
     * Creates new form ServerManu
     */
    public static ServerSocket Serversocket;
    public static Socket socket;
    public static   DataOutputStream data ;
    private  AudioStream audiostream;
      
    public ServerManu() throws IOException {
      super("Server");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CallButton = new javax.swing.JButton();
        ReceiveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CallButton.setText("Call");
        CallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CallButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CallButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 128, 120, -1));

        ReceiveButton.setText("Receive");
        ReceiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceiveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ReceiveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 175, 120, -1));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setText("LANSMIT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 60, 120, 35));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ServerProject/ima.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CallButtonActionPerformed
        try {
          data=new DataOutputStream( socket.getOutputStream());
          data.writeInt(9);
          this.CallButton.setVisible(false);
          this.ReceiveButton.setVisible(false);
       new Thread()
        {
            public void run()
            {
                try {
                    ServerHandler.main(null);
                } catch (Exception ex) {
                }
            }
        }.start();
        } catch (IOException ex) {
            Logger.getLogger(ServerManu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CallButtonActionPerformed

    private void ReceiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceiveButtonActionPerformed
         try 
         {
              AudioPlayer.player.stop(audiostream);
       data=new DataOutputStream( socket.getOutputStream());

          data=new DataOutputStream( socket.getOutputStream());
          
            data.writeInt(10);
             this.setVisible(false);
        new Thread()
        {
            public void run()
            {
                try {
                    ServerHandler.main(null);
                } catch (Exception ex) {
                    Logger.getLogger(ServerManu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }.start();
           
        } catch (IOException ex) {
            
        } catch (Exception ex) {
            Logger.getLogger(ServerManu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ReceiveButtonActionPerformed

  public void playsound() throws Exception 
 {
  String song = "o.wav";
                 FileInputStream s=new FileInputStream(new File(song));
               audiostream =new AudioStream(s);
                AudioPlayer.player.start(audiostream);
         
 } 
 
    public static void main(String args[]) throws Exception {
        Serversocket=new ServerSocket(6666);
        
        final ServerManu menu;
         menu = new ServerManu();
         menu.setVisible(true);
          
        menu.ReceiveButton.setVisible(false);
        while(true)
        { 
             
          socket=Serversocket.accept();
         Thread t= new Thread()
          {
           public void run()
           {
               int i=0;
               while(true)
               
               {
                   try 
                   {  
                      
                       
                       {
                       DataInputStream  data=new DataInputStream(socket.getInputStream());

                                i = data.readInt();
                               System.out.println(i);
                       }

                   } catch (Exception ex) {
                       
                   }
             if(i==11)
             {
               menu.CallButton.setVisible(false);
               menu.ReceiveButton.setVisible(true);
               
                        try {
                            menu.playsound();
                        } catch (Exception ex) {
                        }
             }
             else if(i==12)
             {
                 
               menu.setVisible(false);  
             
             }
             
               }
           }
           
          };
         t.start();
        
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CallButton;
    private javax.swing.JButton ReceiveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
